name: Maven .m2 primer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13

    - name: Set up environment
      run: |
        export
        declare -x SANE_DATE_COMMAND="date +%Y-%m-%d--%H-%M-%S"
        declare -x SANE_DATE_FORMAT="%Y-%m-%d--%H-%M-%S"
        declare -x START_OF_BUILD="$(${SANE_DATE_COMMAND})"
        echo "::set-env name=SANE_DATE_COMMAND::${SANE_DATE_COMMAND}"
        echo "::set-env name=SANE_DATE_FORMAT::${SANE_DATE_FORMAT}"
        echo "::set-env name=START_OF_BUILD::${START_OF_BUILD}"

    - name: Download dependencies with Maven
      run: |
        declare -x ARTIFACT_DIRECTORY="m2-primer-${START_OF_BUILD}.tgz"
        declare -x ARTIFACT_NAME="m2-primer-${START_OF_BUILD}.tgz"
        export
        mvn -B dependency:resolve --file pom.xml
        declare -x ARTIFACT_NAME="m2-primer-${START_OF_BUILD}"
        declare -x ARTIFACT_PATH="$HOME/.m2"
        echo "::set-env name=ARTIFACT_NAME::${ARTIFACT_NAME}"
        echo "::set-env name=ARTIFACT_PATH::${ARTIFACT_PATH}"

      #        echo tar cvzf "${ARTIFACT_NAME}" ~/.m2
      #        tar cvzf "${ARTIFACT_NAME}" ~/.m2

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_PATH }}

#    - name: Deploy to GitHub Package Registry
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      run: |
#        mkdir -p ~/.m2
#        echo "GITHUB_TOKEN=${GITHUB_TOKEN}"
#        echo "<settings><servers><server><id>github</id><username>ggerard</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
#        mvn -B dependency:resolve --file pom.xml
